// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AbaExplorerService 提供 UnityFS 容器（.aba/.asset_bg/.asset_scene）的结构浏览、解包与打包
 * AbaExplorerService browses, unpacks, and packs UnityFS containers (.aba/.asset_bg/.asset_scene)
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AssetExportKindForType 供前端按类型 ID 查询导出形态，空字符串表示不支持单独导出
 * AssetExportKindForType lets the frontend query the export shape by class ID, with an empty string meaning single-object export is unsupported
 */
export function AssetExportKindForType(typeId: number): $CancellablePromise<string> {
    return $Call.ByID(4249346226, typeId);
}

/**
 * ContainerKind 按扩展名判定 UnityFS 容器种类，供前端选择解包入口
 * ContainerKind determines the UnityFS container kind from the extension so the frontend can pick an unpack entry point
 */
export function ContainerKind(path: string): $CancellablePromise<string> {
    return $Call.ByID(602556786, path);
}

/**
 * DefaultPackName 返回打包输出基名的默认建议 / DefaultPackName suggests the default pack output base name
 */
export function DefaultPackName(dirPath: string): $CancellablePromise<string> {
    return $Call.ByID(3467997372, dirPath);
}

/**
 * DefaultUnpackDir 返回解包目标目录的默认建议，沿用 MeidoSerialization 的 <文件名>_unpacked 约定
 * DefaultUnpackDir suggests the default unpack destination following MeidoSerialization's <file name>_unpacked convention
 */
export function DefaultUnpackDir(path: string): $CancellablePromise<string> {
    return $Call.ByID(4117156759, path);
}

/**
 * ExportAsset 把容器内的单个对象写到 outPath
 * 只读取目标 SerializedFile 的必要范围，因此从 500 MB 级别的整合包里取一张贴图也不必解压整个条目
 * ExportAsset writes one object from the container to outPath
 * It reads only the ranges it needs from the target SerializedFile, so pulling one texture out of a 500 MB bundle avoids decompressing the whole entry
 */
export function ExportAsset(containerPath: string, sourceName: string, pathId: string, outPath: string): $CancellablePromise<void> {
    return $Call.ByID(667368957, containerPath, sourceName, pathId, outPath);
}

/**
 * Inspect 解析容器并返回完整结构快照，包含每个 SerializedFile 的对象列表与 m_Container 加载名
 * Inspect parses a container and returns a complete structural snapshot including each SerializedFile's objects and m_Container load names
 */
export function Inspect(path: string): $CancellablePromise<$models.AbaOverview | null> {
    return $Call.ByID(4021962735, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListUnpackedDir 列出一个已存在解包目录中的文件，供前端在不重新解包时浏览并转换
 * ListUnpackedDir lists files in an existing unpacked directory so the frontend can browse and convert without unpacking again
 */
export function ListUnpackedDir(dirPath: string): $CancellablePromise<$models.UnpackResult | null> {
    return $Call.ByID(2324016493, dirPath).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Pack 扫描纯资源目录并在其父目录生成固定 Unity 2022.3.35f1 的 ABA 与配套 CT
 * outputBaseName 为空时取目录名，并去掉 MeidoSerialization 解包时追加的 _unpacked 后缀
 * Pack scans a plain resource directory and emits a fixed Unity 2022.3.35f1 ABA with its companion CT in the parent directory
 * An empty outputBaseName falls back to the directory name with the _unpacked suffix added by MeidoSerialization removed
 */
export function Pack(dirPath: string, outputBaseName: string): $CancellablePromise<$models.PackResult | null> {
    return $Call.ByID(3553670072, dirPath, outputBaseName).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Unpack 将容器提取为不含 metadata、预览图和外部流文件的纯资源目录，并返回产生的文件清单
 * Unpack extracts a container into a plain resource directory without metadata, previews, or external stream files and returns the resulting file list
 */
export function Unpack(path: string, outDir: string): $CancellablePromise<$models.UnpackResult | null> {
    return $Call.ByID(2207782811, path, outDir).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.AbaOverview.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.UnpackResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.PackResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
