// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App 提供应用级能力：文件对话框、文件类型识别、文件信息、预览与版本检查
 * App provides application-level capabilities: file dialogs, file type detection, file info, previews, and update checks
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as COM3D2$0 from "../../MeidoSerialization/v2/service/COM3D2/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CanOpenInModEditor 判断文件是否为 KCES MOD EDITOR 能编辑的格式
 * CanOpenInModEditor reports whether a file is in a format KCES MOD EDITOR can edit
 */
export function CanOpenInModEditor(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(81581672, path);
}

/**
 * CheckLatestVersion 查询 GitHub 上的最新发布版本并与当前版本比较
 * CheckLatestVersion queries the latest GitHub release and compares it with the current version
 */
export function CheckLatestVersion(): $CancellablePromise<$models.VersionCheckResult> {
    return $Call.ByID(24301659).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DetermineFileType 判定 KCES 文件类型，无法识别时 FileType 为 Unknown 供前端按扩展名回退
 * DetermineFileType detects the KCES file type and reports Unknown so the frontend can fall back to the extension
 */
export function DetermineFileType(path: string): $CancellablePromise<COM3D2$0.FileInfo> {
    return $Call.ByID(3853749925, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetAppVersion 返回应用版本 / GetAppVersion returns the application version
 */
export function GetAppVersion(): $CancellablePromise<string> {
    return $Call.ByID(3093159071);
}

/**
 * GetSettings 返回当前的启动期配置，供设置页展示
 * GetSettings returns the current startup configuration for the settings page
 */
export function GetSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(3483909715).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * IsModEditorAvailable 判断系统上是否注册过 KCES MOD EDITOR 的协议
 * 协议由安装器写入，直接解压的绿色版不会注册，此时按钮点了不会有任何反应，需要提前告诉用户
 * IsModEditorAvailable reports whether the KCES MOD EDITOR protocol is registered on this system
 * The installer writes the registration, so a portable copy has none and the button would silently do nothing
 */
export function IsModEditorAvailable(): $CancellablePromise<boolean> {
    return $Call.ByID(683894986);
}

/**
 * OpenInModEditor 通过自定义协议请求 KCES MOD EDITOR 打开一个文件
 * 编辑器已在运行时由它的单实例机制转交给现有窗口，不会每次都启新进程
 * OpenInModEditor asks KCES MOD EDITOR to open a file through the custom protocol
 * A running editor receives it through its single-instance handover instead of starting another process
 */
export function OpenInModEditor(path: string): $CancellablePromise<void> {
    return $Call.ByID(2277443822, path);
}

/**
 * PreviewFile 读取文件开头用于预览，纯文本内容按 UTF-8 返回，二进制内容只报告大小
 * PreviewFile reads the start of a file for preview, returning UTF-8 text for textual content and only size for binary content
 */
export function PreviewFile(path: string): $CancellablePromise<$models.FilePreview | null> {
    return $Call.ByID(1920937600, path).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ProtocolStatus 返回协议名与注册状态
 * 协议由安装器写入，直接解压的绿色版不会注册，此时外部工具唤起不会有任何反应，需要在设置页说清楚
 * ProtocolStatus returns the scheme name and its registration state
 * The installer writes the registration, so a portable copy has none and an external invocation would silently
 * do nothing, which the settings page has to spell out
 */
export function ProtocolStatus(): $CancellablePromise<$models.ProtocolStatus> {
    return $Call.ByID(189603572).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ReadTextFile 以 UTF-8 文本读取文件并去掉 BOM / ReadTextFile reads a file as UTF-8 text and strips the BOM
 */
export function ReadTextFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(298874527, path);
}

/**
 * Reveal 在系统文件管理器中定位路径，参数以数组形式传给进程，不经过 shell 解析
 * Reveal locates a path in the system file manager, passing arguments as an array without shell parsing
 */
export function Reveal(path: string): $CancellablePromise<void> {
    return $Call.ByID(58691023, path);
}

/**
 * SelectDirectory 打开目录选择对话框，用户取消时返回空字符串且错误为 nil
 * SelectDirectory opens a directory-selection dialog and returns an empty string and nil error when cancelled
 */
export function SelectDirectory(title: string): $CancellablePromise<string> {
    return $Call.ByID(3429070449, title);
}

/**
 * SelectFile 打开文件选择对话框，filetype 形如 "*.aba;*.ct"，用户取消时返回空字符串且错误为 nil
 * SelectFile opens a file-selection dialog where filetype looks like "*.aba;*.ct" and returns an empty string and nil error when cancelled
 */
export function SelectFile(filetype: string, fileDisplayName: string): $CancellablePromise<string> {
    return $Call.ByID(1034093716, filetype, fileDisplayName);
}

/**
 * SelectPathToSave 打开保存对话框，suggestedName 预填文件名，用户取消时返回空字符串且错误为 nil
 * 预填名很重要：导出对象时用户不该被要求手打 crc_nt008_line.png 这种名字
 * SelectPathToSave opens a save dialog with suggestedName prefilled and returns an empty string and nil error when cancelled
 * Prefilling matters: exporting an object should not ask the user to type a name like crc_nt008_line.png by hand
 */
export function SelectPathToSave(filetype: string, fileDisplayName: string, suggestedName: string): $CancellablePromise<string> {
    return $Call.ByID(4017277517, filetype, fileDisplayName, suggestedName);
}

/**
 * SetSingleInstance 切换单实例开关，下次启动生效
 * SetSingleInstance toggles single instance and takes effect on the next launch
 */
export function SetSingleInstance(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(1652789197, enabled);
}

/**
 * StartupFile 返回启动时要求打开的路径，可能来自文件关联双击或协议唤起
 * StartupFile returns the path the launch asked to open, either from an association double-click or a protocol invocation
 */
export function StartupFile(): $CancellablePromise<string> {
    return $Call.ByID(3100566529);
}

/**
 * StatPath 查询路径属性，不存在时 Exists 为 false 且不返回错误
 * StatPath queries path attributes and reports Exists as false without an error when the path is missing
 */
export function StatPath(path: string): $CancellablePromise<$models.PathInfo> {
    return $Call.ByID(411158375, path).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * WriteTextFile 以 UTF-8 写入文本文件 / WriteTextFile writes a UTF-8 text file
 */
export function WriteTextFile(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(878918504, path, content);
}

// Private type creation functions
const $$createType0 = $models.VersionCheckResult.createFrom;
const $$createType1 = COM3D2$0.FileInfo.createFrom;
const $$createType2 = $models.Settings.createFrom;
const $$createType3 = $models.FilePreview.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $models.ProtocolStatus.createFrom;
const $$createType6 = $models.PathInfo.createFrom;
