// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConvertService 把解包产物与 KCES 原生文件转换为通用格式，全部直接调用 MeidoSerialization 的 service 包
 * ConvertService converts unpacked assets and KCES native files into common formats by calling MeidoSerialization's service packages directly
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CanPreviewImage 判断文件是否为可渲染的原生 Texture2D 或 Sprite
 * CanPreviewImage reports whether a file is a renderable native Texture2D or Sprite
 */
export function CanPreviewImage(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(4051298430, path);
}

/**
 * Convert 按目标键转换单个文件，outPath 为空时按目标的默认命名写到输入文件旁
 * Convert converts one file for a target key and writes next to the input using the target's default naming when outPath is empty
 */
export function Convert(path: string, target: string, outPath: string): $CancellablePromise<string> {
    return $Call.ByID(1061700150, path, target, outPath);
}

/**
 * ConvertBatch 批量转换，单个文件失败不会中断其余文件，逐条返回结果
 * outDir 为空时输出写到各输入文件旁
 * ConvertBatch converts many files, records each result, and keeps going when one file fails
 * An empty outDir writes each output next to its input file
 */
export function ConvertBatch(paths: string[], target: string, outDir: string): $CancellablePromise<$models.ConvertOutcome[]> {
    return $Call.ByID(2224448962, paths, target, outDir).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * PreviewImage 把原生 Texture2D 或 Sprite 解码为 PNG 并以 data URL 返回
 * 库的转换接口是文件到文件，所以先写入临时目录再读回，返回前删除临时文件
 * PreviewImage decodes a native Texture2D or Sprite into a PNG returned as a data URL
 * The library converts file to file, so the PNG goes to a temporary directory and is removed before returning
 */
export function PreviewImage(path: string): $CancellablePromise<string> {
    return $Call.ByID(2607254146, path);
}

/**
 * Targets 返回一个文件可用的转换目标，同一文件可能同时支持结构化 JSON 与媒体导出
 * Targets returns the conversion targets available for one file, which may support both structured JSON and a media export
 */
export function Targets(path: string): $CancellablePromise<$models.ConvertTarget[]> {
    return $Call.ByID(3960565063, path).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ConvertOutcome.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.ConvertTarget.createFrom;
const $$createType3 = $Create.Array($$createType2);
