// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CtExplorerService 提供 .ct 内容表的浏览、虚拟文件提取、从 ABA 生成与 JSON 互转
 * CtExplorerService browses .ct content tables, extracts virtual files, generates from ABA, and converts to and from JSON
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ConvertFromJson 把编辑 JSON 文件转换回 .ct / ConvertFromJson converts an editing JSON file back into a .ct
 */
export function ConvertFromJson(inputPath: string, outputPath: string): $CancellablePromise<void> {
    return $Call.ByID(2677492799, inputPath, outputPath);
}

/**
 * ConvertToJson 把 .ct 转换为可编辑 JSON 文件 / ConvertToJson converts a .ct into an editable JSON file
 */
export function ConvertToJson(inputPath: string, outputPath: string): $CancellablePromise<void> {
    return $Call.ByID(890231322, inputPath, outputPath);
}

/**
 * ExtractAllVirtualFiles 把全部虚拟文件提取到目录，虚拟文件名先经过文件名清理
 * ExtractAllVirtualFiles extracts every virtual file into a directory after sanitizing each virtual file name
 */
export function ExtractAllVirtualFiles(ctPath: string, outDir: string): $CancellablePromise<string[]> {
    return $Call.ByID(2942386380, ctPath, outDir).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ExtractVirtualFile 把一个虚拟文件写到指定路径 / ExtractVirtualFile writes one virtual file to the given path
 */
export function ExtractVirtualFile(ctPath: string, fileName: string, outPath: string): $CancellablePromise<void> {
    return $Call.ByID(1139414124, ctPath, fileName, outPath);
}

/**
 * GenerateFromAba 读取 .aba 的 AssetBundle 容器并生成配套 .ct，outPath 为空时输出到 .aba 同目录同基名
 * GenerateFromAba reads the AssetBundle container of a .aba and generates its companion .ct, writing next to the .aba with the same base name when outPath is empty
 */
export function GenerateFromAba(abaPath: string, outPath: string): $CancellablePromise<string> {
    return $Call.ByID(2004982345, abaPath, outPath);
}

/**
 * Inspect 解析 .ct 并返回结构快照
 * catalog 解码失败时仍返回虚拟文件表，让损坏或非标准的内容表也能被浏览
 * Inspect parses a .ct and returns a structural snapshot
 * A failed catalog decode still returns the virtual file table so damaged or non-standard content tables remain browsable
 */
export function Inspect(path: string): $CancellablePromise<$models.CtOverview | null> {
    return $Call.ByID(832696494, path).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.CtOverview.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
