// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AbaAsset 是 SerializedFile 中的一个 Unity 对象
 * PathId 走字符串通道，Unity PathID 是随机 64 位值，超出 JS number 的安全整数范围
 * AbaAsset is one Unity object in a SerializedFile
 * PathId travels as a string because a Unity PathID is a random 64-bit value beyond the JS safe-integer range
 */
export class AbaAsset {
    /**
     * Unity PathID 的十进制字符串 / Decimal string of the Unity PathID
     */
    "pathId": string;

    /**
     * Unity class ID / Unity class ID
     */
    "typeId": number;

    /**
     * 类型名 / Type name
     */
    "typeName": string;

    /**
     * 对象 m_Name / Object m_Name
     */
    "name": string;

    /**
     * 序列化数据字节数 / Serialized data size in bytes
     */
    "size": number;

    /**
     * 相对数据区的偏移 / Offset relative to the data area
     */
    "offset": number;

    /**
     * AssetBundle m_Container 加载名 / AssetBundle m_Container load name
     */
    "container": string;

    /** Creates a new AbaAsset instance. */
    constructor($$source: Partial<AbaAsset> = {}) {
        if (!("pathId" in $$source)) {
            this["pathId"] = "";
        }
        if (!("typeId" in $$source)) {
            this["typeId"] = 0;
        }
        if (!("typeName" in $$source)) {
            this["typeName"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("container" in $$source)) {
            this["container"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AbaAsset instance from a string or object.
     */
    static createFrom($$source: any = {}): AbaAsset {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AbaAsset($$parsedSource as Partial<AbaAsset>);
    }
}

/**
 * AbaBlock 是一个压缩数据块的元数据 / AbaBlock is the metadata of one compressed data block
 */
export class AbaBlock {
    /**
     * 块序号 / Block index
     */
    "index": number;

    /**
     * 压缩后大小 / Compressed size
     */
    "compressedSize": number;

    /**
     * 解压后大小 / Decompressed size
     */
    "decompressedSize": number;

    /**
     * 压缩方式名 / Compression name
     */
    "compression": string;

    /**
     * 是否为流式块 / Whether the block is streamed
     */
    "streamed": boolean;

    /**
     * 原始标志位 / Raw flags
     */
    "flags": number;

    /** Creates a new AbaBlock instance. */
    constructor($$source: Partial<AbaBlock> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("compressedSize" in $$source)) {
            this["compressedSize"] = 0;
        }
        if (!("decompressedSize" in $$source)) {
            this["decompressedSize"] = 0;
        }
        if (!("compression" in $$source)) {
            this["compression"] = "";
        }
        if (!("streamed" in $$source)) {
            this["streamed"] = false;
        }
        if (!("flags" in $$source)) {
            this["flags"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AbaBlock instance from a string or object.
     */
    static createFrom($$source: any = {}): AbaBlock {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AbaBlock($$parsedSource as Partial<AbaBlock>);
    }
}

/**
 * AbaDirectory 是容器内一个目录条目 / AbaDirectory is one directory entry inside the container
 */
export class AbaDirectory {
    /**
     * 条目序号 / Entry index
     */
    "index": number;

    /**
     * 条目名 / Entry name
     */
    "name": string;

    /**
     * 相对数据区起始的偏移 / Offset relative to the data-area start
     */
    "offset": number;

    /**
     * 解压后大小 / Decompressed size
     */
    "decompressedSize": number;

    /**
     * 原始标志位 / Raw flags
     */
    "flags": number;

    /**
     * 是否为序列化 AssetsFile / Whether the entry is a serialized AssetsFile
     */
    "serialized": boolean;

    /** Creates a new AbaDirectory instance. */
    constructor($$source: Partial<AbaDirectory> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("decompressedSize" in $$source)) {
            this["decompressedSize"] = 0;
        }
        if (!("flags" in $$source)) {
            this["flags"] = 0;
        }
        if (!("serialized" in $$source)) {
            this["serialized"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AbaDirectory instance from a string or object.
     */
    static createFrom($$source: any = {}): AbaDirectory {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AbaDirectory($$parsedSource as Partial<AbaDirectory>);
    }
}

/**
 * AbaExternalFile 是一条外部文件引用 / AbaExternalFile is one external file reference
 */
export class AbaExternalFile {
    /**
     * 缓存资源虚拟路径 / Virtual cached-asset path
     */
    "assetPath": string;

    /**
     * GUID 十六进制 / Hex GUID
     */
    "guid": string;

    /**
     * 引用类型 / Reference type
     */
    "type": number;

    /**
     * 路径名 / Path name
     */
    "pathName": string;

    /** Creates a new AbaExternalFile instance. */
    constructor($$source: Partial<AbaExternalFile> = {}) {
        if (!("assetPath" in $$source)) {
            this["assetPath"] = "";
        }
        if (!("guid" in $$source)) {
            this["guid"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = 0;
        }
        if (!("pathName" in $$source)) {
            this["pathName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AbaExternalFile instance from a string or object.
     */
    static createFrom($$source: any = {}): AbaExternalFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AbaExternalFile($$parsedSource as Partial<AbaExternalFile>);
    }
}

/**
 * AbaOverview 是一个 UnityFS 容器的完整结构快照
 * AbaOverview is a complete structural snapshot of one UnityFS container
 */
export class AbaOverview {
    /**
     * 容器文件路径 / Container file path
     */
    "path": string;

    /**
     * 容器种类：aba/asset_bg/asset_scene / Container kind
     */
    "kind": string;

    /**
     * 磁盘上的字节数 / On-disk byte count
     */
    "fileSize": number;

    /**
     * UnityFS 签名 / UnityFS signature
     */
    "signature": string;

    /**
     * UnityFS 格式版本 / UnityFS format version
     */
    "formatVersion": number;

    /**
     * 生成版本字符串 / Generation version string
     */
    "generationVersion": string;

    /**
     * Unity 引擎版本 / Unity engine version
     */
    "engineVersion": string;

    /**
     * 头部记录的总大小 / Total size recorded in the header
     */
    "totalFileSize": number;

    /**
     * 块目录元数据压缩方式 / Block-directory metadata compression
     */
    "metadataCompression": string;

    /**
     * 块目录元数据压缩后大小 / Compressed block-directory metadata size
     */
    "metadataCompressed": number;

    /**
     * 块目录元数据解压后大小 / Decompressed block-directory metadata size
     */
    "metadataRaw": number;

    /**
     * 是否组合保存块与目录信息 / Whether block and directory info are combined
     */
    "hasDirectoryInfo": boolean;

    /**
     * 块目录 16 字节哈希的十六进制 / Hex of the 16-byte block-directory hash
     */
    "hash": string;

    /**
     * 压缩数据区总字节数 / Total compressed data-area bytes
     */
    "compressedData": number;

    /**
     * 数据块列表 / Data block list
     */
    "blocks": AbaBlock[];

    /**
     * 目录条目列表 / Directory entry list
     */
    "directories": AbaDirectory[];

    /**
     * 序列化文件及其对象 / Serialized files and their objects
     */
    "serializedFiles": AbaSerializedFile[];

    /**
     * 全部序列化文件中的对象总数 / Total object count across serialized files
     */
    "assetCount": number;

    /** Creates a new AbaOverview instance. */
    constructor($$source: Partial<AbaOverview> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("fileSize" in $$source)) {
            this["fileSize"] = 0;
        }
        if (!("signature" in $$source)) {
            this["signature"] = "";
        }
        if (!("formatVersion" in $$source)) {
            this["formatVersion"] = 0;
        }
        if (!("generationVersion" in $$source)) {
            this["generationVersion"] = "";
        }
        if (!("engineVersion" in $$source)) {
            this["engineVersion"] = "";
        }
        if (!("totalFileSize" in $$source)) {
            this["totalFileSize"] = 0;
        }
        if (!("metadataCompression" in $$source)) {
            this["metadataCompression"] = "";
        }
        if (!("metadataCompressed" in $$source)) {
            this["metadataCompressed"] = 0;
        }
        if (!("metadataRaw" in $$source)) {
            this["metadataRaw"] = 0;
        }
        if (!("hasDirectoryInfo" in $$source)) {
            this["hasDirectoryInfo"] = false;
        }
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("compressedData" in $$source)) {
            this["compressedData"] = 0;
        }
        if (!("blocks" in $$source)) {
            this["blocks"] = [];
        }
        if (!("directories" in $$source)) {
            this["directories"] = [];
        }
        if (!("serializedFiles" in $$source)) {
            this["serializedFiles"] = [];
        }
        if (!("assetCount" in $$source)) {
            this["assetCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AbaOverview instance from a string or object.
     */
    static createFrom($$source: any = {}): AbaOverview {
        const $$createField14_0 = $$createType1;
        const $$createField15_0 = $$createType3;
        const $$createField16_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("blocks" in $$parsedSource) {
            $$parsedSource["blocks"] = $$createField14_0($$parsedSource["blocks"]);
        }
        if ("directories" in $$parsedSource) {
            $$parsedSource["directories"] = $$createField15_0($$parsedSource["directories"]);
        }
        if ("serializedFiles" in $$parsedSource) {
            $$parsedSource["serializedFiles"] = $$createField16_0($$parsedSource["serializedFiles"]);
        }
        return new AbaOverview($$parsedSource as Partial<AbaOverview>);
    }
}

/**
 * AbaSerializedFile 是容器内一个 SerializedFile 的头部、元数据与对象列表
 * AbaSerializedFile is the header, metadata, and object list of one SerializedFile in the container
 */
export class AbaSerializedFile {
    /**
     * 所在目录条目序号 / Owning directory entry index
     */
    "directoryIndex": number;

    /**
     * 目录条目名 / Directory entry name
     */
    "name": string;

    /**
     * SerializedFile 格式版本 / SerializedFile format version
     */
    "formatVersion": number;

    /**
     * Unity 版本字符串 / Unity version string
     */
    "unityVersion": string;

    /**
     * 目标平台 ID / Target platform ID
     */
    "targetPlatform": number;

    /**
     * 是否含类型树 / Whether type tree data is present
     */
    "typeTreeEnabled": boolean;

    /**
     * 是否 Big-Endian / Whether the file is Big-Endian
     */
    "bigEndian": boolean;

    /**
     * 元数据块大小 / Metadata block size
     */
    "metadataSize": number;

    /**
     * 数据区起始偏移 / Data-area start offset
     */
    "dataOffset": number;

    /**
     * SerializedFile 总大小 / Total SerializedFile size
     */
    "fileSize": number;

    /**
     * 类型树定义数量 / Type tree definition count
     */
    "typeCount": number;

    /**
     * 元数据尾部用户信息 / User information at the metadata tail
     */
    "userInformation": string;

    /**
     * 外部文件引用 / External file references
     */
    "externalFiles": AbaExternalFile[];

    /**
     * 对象列表 / Object list
     */
    "assets": AbaAsset[];

    /**
     * m_Container 读取失败原因，成功时为空 / Reason m_Container reading failed, empty on success
     */
    "containerError": string;

    /** Creates a new AbaSerializedFile instance. */
    constructor($$source: Partial<AbaSerializedFile> = {}) {
        if (!("directoryIndex" in $$source)) {
            this["directoryIndex"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("formatVersion" in $$source)) {
            this["formatVersion"] = 0;
        }
        if (!("unityVersion" in $$source)) {
            this["unityVersion"] = "";
        }
        if (!("targetPlatform" in $$source)) {
            this["targetPlatform"] = 0;
        }
        if (!("typeTreeEnabled" in $$source)) {
            this["typeTreeEnabled"] = false;
        }
        if (!("bigEndian" in $$source)) {
            this["bigEndian"] = false;
        }
        if (!("metadataSize" in $$source)) {
            this["metadataSize"] = 0;
        }
        if (!("dataOffset" in $$source)) {
            this["dataOffset"] = 0;
        }
        if (!("fileSize" in $$source)) {
            this["fileSize"] = 0;
        }
        if (!("typeCount" in $$source)) {
            this["typeCount"] = 0;
        }
        if (!("userInformation" in $$source)) {
            this["userInformation"] = "";
        }
        if (!("externalFiles" in $$source)) {
            this["externalFiles"] = [];
        }
        if (!("assets" in $$source)) {
            this["assets"] = [];
        }
        if (!("containerError" in $$source)) {
            this["containerError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AbaSerializedFile instance from a string or object.
     */
    static createFrom($$source: any = {}): AbaSerializedFile {
        const $$createField12_0 = $$createType7;
        const $$createField13_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("externalFiles" in $$parsedSource) {
            $$parsedSource["externalFiles"] = $$createField12_0($$parsedSource["externalFiles"]);
        }
        if ("assets" in $$parsedSource) {
            $$parsedSource["assets"] = $$createField13_0($$parsedSource["assets"]);
        }
        return new AbaSerializedFile($$parsedSource as Partial<AbaSerializedFile>);
    }
}

/**
 * ConvertOutcome 是一个文件的转换结果 / ConvertOutcome is the conversion result of one file
 */
export class ConvertOutcome {
    /**
     * 输入路径 / Input path
     */
    "inputPath": string;

    /**
     * 输出路径，失败时为空 / Output path, empty on failure
     */
    "outputPath": string;

    /**
     * 使用的目标键 / Target key used
     */
    "target": string;

    /**
     * 失败原因，成功时为空 / Failure reason, empty on success
     */
    "error": string;

    /** Creates a new ConvertOutcome instance. */
    constructor($$source: Partial<ConvertOutcome> = {}) {
        if (!("inputPath" in $$source)) {
            this["inputPath"] = "";
        }
        if (!("outputPath" in $$source)) {
            this["outputPath"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConvertOutcome instance from a string or object.
     */
    static createFrom($$source: any = {}): ConvertOutcome {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConvertOutcome($$parsedSource as Partial<ConvertOutcome>);
    }
}

/**
 * ConvertTarget 是一个文件可用的转换目标 / ConvertTarget is one available conversion target for a file
 */
export class ConvertTarget {
    /**
     * 目标键：json/png/glb/gltf/audio/csv / Target key: json/png/glb/gltf/audio/csv
     */
    "key": string;

    /**
     * 输出扩展名，audio 在转换时探测所以为空 / Output extension, empty for audio which is detected at conversion time
     */
    "ext": string;

    /** Creates a new ConvertTarget instance. */
    constructor($$source: Partial<ConvertTarget> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("ext" in $$source)) {
            this["ext"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConvertTarget instance from a string or object.
     */
    static createFrom($$source: any = {}): ConvertTarget {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConvertTarget($$parsedSource as Partial<ConvertTarget>);
    }
}

/**
 * CtCatalog 是 catalog 虚拟文件的解码结果
 * Hash 与 CreateTime 走字符串通道，两者是 64 位值，超出 JS number 的安全整数范围
 * CtCatalog is the decoded content of the catalog virtual file
 * Hash and CreateTime travel as strings because both are 64-bit values beyond the JS safe-integer range
 */
export class CtCatalog {
    /**
     * assetBundle 或 virtualAsset / assetBundle or virtualAsset
     */
    "kind": string;

    /**
     * 序列化版本 / Serialization version
     */
    "version": number;

    /**
     * 资源分类标志位原值 / Raw resource-category flags
     */
    "catalogType": number;

    /**
     * 标志位拆解出的分类名 / Category names decoded from the flags
     */
    "catalogTypeNames": string[];

    /**
     * 包类型原值 / Raw package type
     */
    "packageType": number;

    /**
     * 包类型名 / Package type name
     */
    "packageTypeName": string;

    /**
     * 排序优先级 / Ordering priority
     */
    "priority": number;

    /**
     * catalog 名称 / Catalog name
     */
    "name": string;

    /**
     * catalog 子名称 / Catalog sub-name
     */
    "subName": string;

    /**
     * catalog 哈希的十进制字符串 / Decimal string of the catalog hash
     */
    "hash": string;

    /**
     * 创建时间原值的十进制字符串 / Decimal string of the raw creation-time value
     */
    "createTime": string;

    /**
     * AssetBundle 是否加密 / Whether AssetBundles are encrypted
     */
    "isEncrypted": boolean;

    /**
     * AssetBundle 资源文件名 / AssetBundle resource file names
     */
    "resourceFileNames": string[];

    /**
     * 扩展名虚拟文件列表 / Extension-name virtual-file list
     */
    "extensionList": string[];

    /**
     * catalog 条目 / Catalog items
     */
    "items": CtCatalogItem[];

    /** Creates a new CtCatalog instance. */
    constructor($$source: Partial<CtCatalog> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("catalogType" in $$source)) {
            this["catalogType"] = 0;
        }
        if (!("catalogTypeNames" in $$source)) {
            this["catalogTypeNames"] = [];
        }
        if (!("packageType" in $$source)) {
            this["packageType"] = 0;
        }
        if (!("packageTypeName" in $$source)) {
            this["packageTypeName"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("subName" in $$source)) {
            this["subName"] = "";
        }
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = "";
        }
        if (!("isEncrypted" in $$source)) {
            this["isEncrypted"] = false;
        }
        if (!("resourceFileNames" in $$source)) {
            this["resourceFileNames"] = [];
        }
        if (!("extensionList" in $$source)) {
            this["extensionList"] = [];
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CtCatalog instance from a string or object.
     */
    static createFrom($$source: any = {}): CtCatalog {
        const $$createField3_0 = $$createType10;
        const $$createField12_0 = $$createType10;
        const $$createField13_0 = $$createType10;
        const $$createField14_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("catalogTypeNames" in $$parsedSource) {
            $$parsedSource["catalogTypeNames"] = $$createField3_0($$parsedSource["catalogTypeNames"]);
        }
        if ("resourceFileNames" in $$parsedSource) {
            $$parsedSource["resourceFileNames"] = $$createField12_0($$parsedSource["resourceFileNames"]);
        }
        if ("extensionList" in $$parsedSource) {
            $$parsedSource["extensionList"] = $$createField13_0($$parsedSource["extensionList"]);
        }
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField14_0($$parsedSource["items"]);
        }
        return new CtCatalog($$parsedSource as Partial<CtCatalog>);
    }
}

/**
 * CtCatalogItem 是一条 catalog 资源条目，同时覆盖 AssetBundle 与 VirtualAsset 两种布局
 * CtCatalogItem is one catalog resource entry covering both the AssetBundle and VirtualAsset layouts
 */
export class CtCatalogItem {
    /**
     * 资源名称 / Resource name
     */
    "name": string;

    /**
     * 资源哈希的十进制字符串 / Decimal string of the resource hash
     */
    "hash": string;

    /**
     * ResourceFileNames 索引，VirtualAsset 恒为 -1 / Index into ResourceFileNames, always -1 for VirtualAsset
     */
    "resourceIndex": number;

    /**
     * VirtualAsset 的 Unity 工程资源路径 / Unity project asset path for VirtualAsset
     */
    "assetPath": string;

    /** Creates a new CtCatalogItem instance. */
    constructor($$source: Partial<CtCatalogItem> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("resourceIndex" in $$source)) {
            this["resourceIndex"] = 0;
        }
        if (!("assetPath" in $$source)) {
            this["assetPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CtCatalogItem instance from a string or object.
     */
    static createFrom($$source: any = {}): CtCatalogItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CtCatalogItem($$parsedSource as Partial<CtCatalogItem>);
    }
}

/**
 * CtDirectory 是内容表中的一个子目录 / CtDirectory is one child directory in a content table
 */
export class CtDirectory {
    /**
     * 规范斜杠分隔路径 / Canonical slash-separated path
     */
    "path": string;

    /**
     * 子 VirtualDirectory 版本 / Child VirtualDirectory version
     */
    "version": number;

    /** Creates a new CtDirectory instance. */
    constructor($$source: Partial<CtDirectory> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CtDirectory instance from a string or object.
     */
    static createFrom($$source: any = {}): CtDirectory {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CtDirectory($$parsedSource as Partial<CtDirectory>);
    }
}

/**
 * CtExtensionName 是扩展名表中的一条记录 / CtExtensionName is one record in an extension name list
 */
export class CtExtensionName {
    /**
     * 资源名称 / Resource name
     */
    "name": string;

    /**
     * 哈希的十进制字符串 / Decimal string of the hash
     */
    "hash": string;

    /** Creates a new CtExtensionName instance. */
    constructor($$source: Partial<CtExtensionName> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CtExtensionName instance from a string or object.
     */
    static createFrom($$source: any = {}): CtExtensionName {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CtExtensionName($$parsedSource as Partial<CtExtensionName>);
    }
}

/**
 * CtExtensionNameList 是一个扩展名分组下的名称表 / CtExtensionNameList is the name list under one extension group
 */
export class CtExtensionNameList {
    /**
     * ExtensionNameLists 的键 / Key in ExtensionNameLists
     */
    "key": string;

    /**
     * 游戏字段 extention 的值 / Value of the game's extention field
     */
    "extension": string;

    /**
     * 名称与哈希条目 / Name and hash entries
     */
    "data": CtExtensionName[];

    /** Creates a new CtExtensionNameList instance. */
    constructor($$source: Partial<CtExtensionNameList> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("extension" in $$source)) {
            this["extension"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CtExtensionNameList instance from a string or object.
     */
    static createFrom($$source: any = {}): CtExtensionNameList {
        const $$createField2_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new CtExtensionNameList($$parsedSource as Partial<CtExtensionNameList>);
    }
}

/**
 * CtOverview 是一个 .ct 内容表的完整结构快照
 * CtOverview is a complete structural snapshot of one .ct content table
 */
export class CtOverview {
    /**
     * .ct 文件路径 / .ct file path
     */
    "path": string;

    /**
     * 磁盘上的字节数 / On-disk byte count
     */
    "fileSize": number;

    /**
     * 根 VirtualDirectory 版本 / Root VirtualDirectory version
     */
    "version": number;

    /**
     * 外层封装：legacy 或 extended / Outer framing, legacy or extended
     */
    "framing": string;

    /**
     * 子目录及其版本 / Child directories and their versions
     */
    "directories": CtDirectory[];

    /**
     * 虚拟文件表 / Virtual file table
     */
    "files": CtVirtualFile[];

    /**
     * 解码后的 catalog，缺失或解析失败时为空 / Decoded catalog, empty when missing or unparsable
     */
    "catalog": CtCatalog | null;

    /**
     * catalog 解析失败原因 / Reason catalog parsing failed
     */
    "catalogError": string;

    /**
     * 按扩展名分组的名称表 / Name lists grouped by extension
     */
    "extensions": CtExtensionNameList[];

    /** Creates a new CtOverview instance. */
    constructor($$source: Partial<CtOverview> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("fileSize" in $$source)) {
            this["fileSize"] = 0;
        }
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("framing" in $$source)) {
            this["framing"] = "";
        }
        if (!("directories" in $$source)) {
            this["directories"] = [];
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("catalog" in $$source)) {
            this["catalog"] = null;
        }
        if (!("catalogError" in $$source)) {
            this["catalogError"] = "";
        }
        if (!("extensions" in $$source)) {
            this["extensions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CtOverview instance from a string or object.
     */
    static createFrom($$source: any = {}): CtOverview {
        const $$createField4_0 = $$createType16;
        const $$createField5_0 = $$createType18;
        const $$createField6_0 = $$createType20;
        const $$createField8_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("directories" in $$parsedSource) {
            $$parsedSource["directories"] = $$createField4_0($$parsedSource["directories"]);
        }
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField5_0($$parsedSource["files"]);
        }
        if ("catalog" in $$parsedSource) {
            $$parsedSource["catalog"] = $$createField6_0($$parsedSource["catalog"]);
        }
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField8_0($$parsedSource["extensions"]);
        }
        return new CtOverview($$parsedSource as Partial<CtOverview>);
    }
}

/**
 * CtVirtualFile 是内容表中的一个虚拟文件 / CtVirtualFile is one virtual file in a content table
 */
export class CtVirtualFile {
    /**
     * 虚拟文件名 / Virtual file name
     */
    "name": string;

    /**
     * 在 .ct 中的绝对字节偏移 / Absolute byte offset inside the .ct
     */
    "position": number;

    /**
     * 字节数 / Byte count
     */
    "size": number;

    /** Creates a new CtVirtualFile instance. */
    constructor($$source: Partial<CtVirtualFile> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("position" in $$source)) {
            this["position"] = 0;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CtVirtualFile instance from a string or object.
     */
    static createFrom($$source: any = {}): CtVirtualFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CtVirtualFile($$parsedSource as Partial<CtVirtualFile>);
    }
}

/**
 * FacetCount 是一个过滤项及其命中数 / FacetCount is one filter value and its count
 */
export class FacetCount {
    /**
     * 过滤值 / Filter value
     */
    "value": string;

    /**
     * 索引中的数量 / Count in the index
     */
    "count": number;

    /** Creates a new FacetCount instance. */
    constructor($$source: Partial<FacetCount> = {}) {
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FacetCount instance from a string or object.
     */
    static createFrom($$source: any = {}): FacetCount {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FacetCount($$parsedSource as Partial<FacetCount>);
    }
}

/**
 * FilePreview 是一个文件的预览结果
 * 二进制内容不做十六进制转储：那对排查 KCES 资源没有帮助，需要看内部结构时应该先转换成 JSON
 * FilePreview is the preview result of one file
 * Binary content gets no hex dump because that does not help with KCES assets; convert to JSON to inspect the structure
 */
export class FilePreview {
    /**
     * 文件路径 / File path
     */
    "path": string;

    /**
     * 文件总字节数 / Total file byte count
     */
    "size": number;

    /**
     * 内容是否可按 UTF-8 文本展示 / Whether the content displays as UTF-8 text
     */
    "isText": boolean;

    /**
     * 文本内容，IsText 为 false 时为空 / Text content, empty when IsText is false
     */
    "text": string;

    /**
     * 是否因超出上限被截断 / Whether the preview was truncated at the limit
     */
    "truncated": boolean;

    /** Creates a new FilePreview instance. */
    constructor($$source: Partial<FilePreview> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("isText" in $$source)) {
            this["isText"] = false;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FilePreview instance from a string or object.
     */
    static createFrom($$source: any = {}): FilePreview {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FilePreview($$parsedSource as Partial<FilePreview>);
    }
}

/**
 * IndexFacets 是当前索引里出现过的扩展名与来源层，供前端生成过滤选项
 * IndexFacets lists the extensions and origin layers present in the current index so the frontend can build filters
 */
export class IndexFacets {
    /**
     * 扩展名及其数量 / Extensions and their counts
     */
    "extensions": FacetCount[];

    /**
     * 来源层及其数量 / Origin layers and their counts
     */
    "origins": FacetCount[];

    /** Creates a new IndexFacets instance. */
    constructor($$source: Partial<IndexFacets> = {}) {
        if (!("extensions" in $$source)) {
            this["extensions"] = [];
        }
        if (!("origins" in $$source)) {
            this["origins"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexFacets instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexFacets {
        const $$createField0_0 = $$createType24;
        const $$createField1_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField0_0($$parsedSource["extensions"]);
        }
        if ("origins" in $$parsedSource) {
            $$parsedSource["origins"] = $$createField1_0($$parsedSource["origins"]);
        }
        return new IndexFacets($$parsedSource as Partial<IndexFacets>);
    }
}

/**
 * IndexOptions 是一次索引构建的输入 / IndexOptions is the input of one index build
 */
export class IndexOptions {
    /**
     * 要扫描的根目录 / Root directory to scan
     */
    "root": string;

    /**
     * Deep 打开后会解析 .menuassets/.materialassets/.pmatassets，取出 .menu/.mate/.pmat 这些
     * 只存在于容器内部、catalog 不会列出的名字
     * Deep parses .menuassets, .materialassets, and .pmatassets to recover the .menu, .mate, and .pmat names
     * that exist only inside those containers and are never listed by a catalog
     */
    "deep": boolean;

    /**
     * Refresh 打开后忽略磁盘缓存，从头重扫每个文件
     * 指纹只看大小与修改时间，理论上存在改了内容却保持两者不变的情况，这个开关是那种情况的出路
     * Refresh ignores the on-disk cache and rescans every file from scratch
     * Fingerprints only compare size and modification time, so content can in principle change while both
     * stay put, and this switch is the way out of that case
     */
    "refresh": boolean;

    /** Creates a new IndexOptions instance. */
    constructor($$source: Partial<IndexOptions> = {}) {
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("deep" in $$source)) {
            this["deep"] = false;
        }
        if (!("refresh" in $$source)) {
            this["refresh"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IndexOptions($$parsedSource as Partial<IndexOptions>);
    }
}

/**
 * IndexProgress 是构建过程中推送给前端的进度 / IndexProgress is the progress pushed to the frontend during a build
 */
export class IndexProgress {
    /**
     * 已处理文件数 / Files processed
     */
    "done": number;

    /**
     * 待处理文件总数 / Total files to process
     */
    "total": number;

    /**
     * 已收集的名字数 / Names collected so far
     */
    "names": number;

    /**
     * 最近处理的文件名 / Most recently processed file name
     */
    "current": string;

    /**
     * 构建是否已结束 / Whether the build has finished
     */
    "finished": boolean;

    /** Creates a new IndexProgress instance. */
    constructor($$source: Partial<IndexProgress> = {}) {
        if (!("done" in $$source)) {
            this["done"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("names" in $$source)) {
            this["names"] = 0;
        }
        if (!("current" in $$source)) {
            this["current"] = "";
        }
        if (!("finished" in $$source)) {
            this["finished"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IndexProgress($$parsedSource as Partial<IndexProgress>);
    }
}

/**
 * IndexStats 是一次索引构建的结果概况 / IndexStats summarizes the outcome of one index build
 */
export class IndexStats {
    /**
     * 被索引的根目录 / Indexed root directory
     */
    "root": string;

    /**
     * 是否解析了容器内部名 / Whether inner container names were parsed
     */
    "deep": boolean;

    /**
     * 索引是否可用 / Whether an index is available
     */
    "ready": boolean;

    /**
     * 是否正在构建 / Whether a build is running
     */
    "building": boolean;

    /**
     * 上次构建是否被取消 / Whether the last build was cancelled
     */
    "cancelled": boolean;

    /**
     * 成功解析的 .ct 数 / Successfully parsed .ct count
     */
    "catalogs": number;

    /**
     * 成功打开的容器数 / Successfully opened container count
     */
    "containers": number;

    /**
     * 索引中的名字总数 / Total names in the index
     */
    "names": number;

    /**
     * 其中来自容器内部的名字数 / Names among them coming from inside containers
     */
    "innerNames": number;

    /**
     * 直接沿用磁盘缓存的来源数 / Sources taken straight from the on-disk cache
     */
    "reused": number;

    /**
     * 整份索引是否直接来自缓存 / Whether the whole index came straight from the cache
     */
    "fromCache": boolean;

    /**
     * 构建耗时毫秒 / Build duration in milliseconds
     */
    "elapsedMs": number;

    /**
     * 跳过的文件及原因 / Skipped files and their reasons
     */
    "warnings": string[];

    /** Creates a new IndexStats instance. */
    constructor($$source: Partial<IndexStats> = {}) {
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("deep" in $$source)) {
            this["deep"] = false;
        }
        if (!("ready" in $$source)) {
            this["ready"] = false;
        }
        if (!("building" in $$source)) {
            this["building"] = false;
        }
        if (!("cancelled" in $$source)) {
            this["cancelled"] = false;
        }
        if (!("catalogs" in $$source)) {
            this["catalogs"] = 0;
        }
        if (!("containers" in $$source)) {
            this["containers"] = 0;
        }
        if (!("names" in $$source)) {
            this["names"] = 0;
        }
        if (!("innerNames" in $$source)) {
            this["innerNames"] = 0;
        }
        if (!("reused" in $$source)) {
            this["reused"] = 0;
        }
        if (!("fromCache" in $$source)) {
            this["fromCache"] = false;
        }
        if (!("elapsedMs" in $$source)) {
            this["elapsedMs"] = 0;
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexStats instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexStats {
        const $$createField12_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField12_0($$parsedSource["warnings"]);
        }
        return new IndexStats($$parsedSource as Partial<IndexStats>);
    }
}

/**
 * PackResult 是一次打包的结果，包含两个输出路径与打包器给出的游戏加载警告
 * PackResult is the outcome of one pack operation with both output paths and the packer's game-loading warnings
 */
export class PackResult {
    /**
     * 生成的 ABA 路径 / Path of the generated ABA
     */
    "abaPath": string;

    /**
     * 生成的配套 CT 路径 / Path of the generated companion CT
     */
    "ctPath": string;

    /**
     * 打包器输出的警告，例如包名与内部容器名不匹配 / Warnings from the packer, such as a bundle name that does not match the inner container names
     */
    "warnings": string[];

    /** Creates a new PackResult instance. */
    constructor($$source: Partial<PackResult> = {}) {
        if (!("abaPath" in $$source)) {
            this["abaPath"] = "";
        }
        if (!("ctPath" in $$source)) {
            this["ctPath"] = "";
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PackResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PackResult {
        const $$createField2_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField2_0($$parsedSource["warnings"]);
        }
        return new PackResult($$parsedSource as Partial<PackResult>);
    }
}

/**
 * PathInfo 是一个路径的基础属性 / PathInfo holds the basic attributes of one path
 */
export class PathInfo {
    /**
     * 查询的路径 / Queried path
     */
    "path": string;

    /**
     * 路径是否存在 / Whether the path exists
     */
    "exists": boolean;

    /**
     * 是否为目录 / Whether the path is a directory
     */
    "isDir": boolean;

    /**
     * 文件字节数，目录为 0 / File byte count, zero for directories
     */
    "size": number;

    /**
     * 最后修改时间的 RFC3339 表示 / Last modification time in RFC3339
     */
    "modified": string;

    /** Creates a new PathInfo instance. */
    constructor($$source: Partial<PathInfo> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("modified" in $$source)) {
            this["modified"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PathInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PathInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PathInfo($$parsedSource as Partial<PathInfo>);
    }
}

/**
 * ProtocolStatus 是自定义协议的当前状态，设置页用它说明协议现在能不能用
 * ProtocolStatus is the current state of the custom protocol so the settings page can explain whether it works
 */
export class ProtocolStatus {
    /**
     * 协议名，不含 :// / Scheme name without ://
     */
    "scheme": string;

    /**
     * 系统上是否注册过 / Whether it is registered on this system
     */
    "registered": boolean;

    /** Creates a new ProtocolStatus instance. */
    constructor($$source: Partial<ProtocolStatus> = {}) {
        if (!("scheme" in $$source)) {
            this["scheme"] = "";
        }
        if (!("registered" in $$source)) {
            this["registered"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProtocolStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ProtocolStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProtocolStatus($$parsedSource as Partial<ProtocolStatus>);
    }
}

/**
 * SearchHit 是一条命中记录 / SearchHit is one matched record
 */
export class SearchHit {
    /**
     * 资源名 / Resource name
     */
    "name": string;

    /**
     * 资源扩展名 / Resource extension
     */
    "extension": string;

    /**
     * .menu 的游戏内显示名或 .mate 的 shader 名 / In-game display name of a .menu or shader name of a .mate
     */
    "detail": string;

    /**
     * 名字来源层 / Origin layer of the name
     */
    "origin": string;

    /**
     * 宿主容器条目名，直接资源为空 / Owning container entry name, empty for direct resources
     */
    "owner": string;

    /**
     * 所在容器绝对路径，未能定位时为空 / Absolute path of the owning container, empty when it could not be located
     */
    "containerPath": string;

    /**
     * 所在容器文件名 / File name of the owning container
     */
    "containerName": string;

    /**
     * 配套 .ct 绝对路径，没有则为空 / Absolute path of the paired .ct, empty when absent
     */
    "catalogPath": string;

    /** Creates a new SearchHit instance. */
    constructor($$source: Partial<SearchHit> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("extension" in $$source)) {
            this["extension"] = "";
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }
        if (!("origin" in $$source)) {
            this["origin"] = "";
        }
        if (!("owner" in $$source)) {
            this["owner"] = "";
        }
        if (!("containerPath" in $$source)) {
            this["containerPath"] = "";
        }
        if (!("containerName" in $$source)) {
            this["containerName"] = "";
        }
        if (!("catalogPath" in $$source)) {
            this["catalogPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchHit instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchHit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchHit($$parsedSource as Partial<SearchHit>);
    }
}

/**
 * SearchQuery 是一次查询的条件 / SearchQuery is the condition of one query
 */
export class SearchQuery {
    /**
     * 匹配文本，大小写不敏感子串 / Match text, a case-insensitive substring
     */
    "text": string;

    /**
     * 限定扩展名，空表示不限 / Restrict to extensions, empty means no restriction
     */
    "extensions": string[];

    /**
     * 限定来源层，空表示不限 / Restrict to origin layers, empty means no restriction
     */
    "origins": string[];

    /**
     * 返回条数上限 / Maximum hits to return
     */
    "limit": number;

    /** Creates a new SearchQuery instance. */
    constructor($$source: Partial<SearchQuery> = {}) {
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("extensions" in $$source)) {
            this["extensions"] = [];
        }
        if (!("origins" in $$source)) {
            this["origins"] = [];
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchQuery {
        const $$createField1_0 = $$createType10;
        const $$createField2_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField1_0($$parsedSource["extensions"]);
        }
        if ("origins" in $$parsedSource) {
            $$parsedSource["origins"] = $$createField2_0($$parsedSource["origins"]);
        }
        return new SearchQuery($$parsedSource as Partial<SearchQuery>);
    }
}

/**
 * SearchResult 是一次查询的结果 / SearchResult is the outcome of one query
 */
export class SearchResult {
    /**
     * 命中记录，已按相关度排序 / Matched records ordered by relevance
     */
    "hits": SearchHit[];

    /**
     * 命中总数，未被上限裁剪 / Total match count before the limit is applied
     */
    "total": number;

    /**
     * 是否因上限被裁剪 / Whether the limit truncated the list
     */
    "truncated": boolean;

    /**
     * 查询耗时毫秒 / Query duration in milliseconds
     */
    "elapsedMs": number;

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("hits" in $$source)) {
            this["hits"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }
        if (!("elapsedMs" in $$source)) {
            this["elapsedMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        const $$createField0_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hits" in $$parsedSource) {
            $$parsedSource["hits"] = $$createField0_0($$parsedSource["hits"]);
        }
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

/**
 * Settings 是必须在应用启动前就读到的配置
 * 单实例要在 application.New 时就决定，那时前端还没起来、localStorage 读不到，所以这类设置只能存文件
 * Settings holds configuration that must be known before the application starts
 * Single instance is decided at application.New, before the frontend exists and localStorage is reachable,
 * so settings of this kind have to live in a file
 */
export class Settings {
    /**
     * SingleInstance 为 true 时只允许一个实例运行，协议唤起与文件关联都转交给已有窗口
     * 关闭后每次唤起都会开新窗口，冷启动仍会打开目标文件
     * When true only one instance runs and protocol or association opens are handed to the existing window
     * When off each invocation opens another window, which still opens the target file on the cold-start path
     */
    "singleInstance": boolean;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("singleInstance" in $$source)) {
            this["singleInstance"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

/**
 * UnpackResult 是一次解包的结果 / UnpackResult is the outcome of one unpack operation
 */
export class UnpackResult {
    /**
     * 解包输出目录 / Unpack output directory
     */
    "outDir": string;

    /**
     * 解包产生的文件 / Files produced by the unpack
     */
    "files": UnpackedFile[];

    /** Creates a new UnpackResult instance. */
    constructor($$source: Partial<UnpackResult> = {}) {
        if (!("outDir" in $$source)) {
            this["outDir"] = "";
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UnpackResult instance from a string or object.
     */
    static createFrom($$source: any = {}): UnpackResult {
        const $$createField1_0 = $$createType28;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField1_0($$parsedSource["files"]);
        }
        return new UnpackResult($$parsedSource as Partial<UnpackResult>);
    }
}

/**
 * UnpackedFile 是解包目录中的一个文件 / UnpackedFile is one file in an unpacked directory
 */
export class UnpackedFile {
    /**
     * 相对解包根目录的斜杠分隔路径 / Slash-separated path relative to the unpack root
     */
    "relPath": string;

    /**
     * 绝对路径 / Absolute path
     */
    "absPath": string;

    /**
     * 顶层类型目录名，如 Texture2D / Top-level type directory name such as Texture2D
     */
    "kind": string;

    /**
     * 字节数 / Byte count
     */
    "size": number;

    /** Creates a new UnpackedFile instance. */
    constructor($$source: Partial<UnpackedFile> = {}) {
        if (!("relPath" in $$source)) {
            this["relPath"] = "";
        }
        if (!("absPath" in $$source)) {
            this["absPath"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UnpackedFile instance from a string or object.
     */
    static createFrom($$source: any = {}): UnpackedFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UnpackedFile($$parsedSource as Partial<UnpackedFile>);
    }
}

/**
 * VersionCheckResult 是版本检查结果 / VersionCheckResult is the outcome of an update check
 */
export class VersionCheckResult {
    /**
     * 当前版本 / Current version
     */
    "currentVersion": string;

    /**
     * 最新发布版本 / Latest released version
     */
    "latestVersion": string;

    /**
     * 最新版本是否更高 / Whether the latest version is higher
     */
    "isNewer": boolean;

    /** Creates a new VersionCheckResult instance. */
    constructor($$source: Partial<VersionCheckResult> = {}) {
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("isNewer" in $$source)) {
            this["isNewer"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): VersionCheckResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionCheckResult($$parsedSource as Partial<VersionCheckResult>);
    }
}

// Private type creation functions
const $$createType0 = AbaBlock.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = AbaDirectory.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = AbaSerializedFile.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = AbaExternalFile.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = AbaAsset.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Array($Create.Any);
const $$createType11 = CtCatalogItem.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = CtExtensionName.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = CtDirectory.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = CtVirtualFile.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = CtCatalog.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = CtExtensionNameList.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = FacetCount.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = SearchHit.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = UnpackedFile.createFrom;
const $$createType28 = $Create.Array($$createType27);
