// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SearchService 在一个目录树上建立资源名索引，用于回答"这个名字在哪个 aba 里"
 * 游戏按名字加载资源，而名字分布在两层：.ct 的 catalog 列出容器里的资源，
 * .menu/.mate/.pmat 这类名字只存在于容器内部的 .menuassets/.materialassets/.pmatassets 里，catalog 不会列
 * SearchService indexes resource names across a directory tree to answer "which .aba holds this name"
 * The game loads resources by name, and names live on two layers: a .ct catalog lists the resources of a container,
 * while names such as .menu, .mate, and .pmat exist only inside the .menuassets, .materialassets, and .pmatassets
 * entries within a container and never appear in a catalog
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BuildIndex 在 root 下建立名字索引，期间按文件推送进度事件，可用 CancelIndex 中断
 * 索引常驻内存直到进程退出或再次构建，因此重复查询是毫秒级的
 * BuildIndex builds a name index under root, pushes a progress event per file, and can be interrupted with CancelIndex
 * The index stays in memory until the process exits or another build starts, so repeated queries take milliseconds
 */
export function BuildIndex(options: $models.IndexOptions): $CancellablePromise<$models.IndexStats> {
    return $Call.ByID(2356515890, options).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CancelIndex 请求中断正在进行的构建，已建成的索引保持不变
 * 没有构建在跑时是空操作，不会影响下一次 BuildIndex
 * CancelIndex asks a running build to stop and leaves an already built index untouched
 * It is a no-op when no build is running and never affects the next BuildIndex
 */
export function CancelIndex(): $CancellablePromise<void> {
    return $Call.ByID(1670341992);
}

/**
 * ClearCache 删除一个根目录的磁盘缓存 / ClearCache deletes the on-disk cache of a root directory
 */
export function ClearCache(root: string): $CancellablePromise<void> {
    return $Call.ByID(979253115, root);
}

/**
 * ClearIndex 丢弃当前索引 / ClearIndex discards the current index
 */
export function ClearIndex(): $CancellablePromise<void> {
    return $Call.ByID(3303107181);
}

/**
 * Facets 统计索引里各扩展名与来源层的数量
 * Facets counts the extensions and origin layers in the index
 */
export function Facets(): $CancellablePromise<$models.IndexFacets> {
    return $Call.ByID(1484244582).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * IndexStatus 返回当前索引状态，供前端在页面挂载时恢复显示
 * IndexStatus returns the current index status so the frontend can restore its display on mount
 */
export function IndexStatus(): $CancellablePromise<$models.IndexStats> {
    return $Call.ByID(3616062180).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * LoadCachedIndex 直接装载一个根目录的磁盘缓存，只在缓存完整且每个文件都没变过时成功
 * 有任何一处对不上就返回未就绪，让用户去走构建：这里悄悄用半份缓存会让搜索结果少东西却看不出来
 * LoadCachedIndex loads the on-disk cache of a root directory and succeeds only when the cache is complete
 * and every file is unchanged
 * Any mismatch returns a not-ready status so the user runs a build instead, because silently serving half a
 * cache would drop results without any visible sign
 */
export function LoadCachedIndex(options: $models.IndexOptions): $CancellablePromise<$models.IndexStats> {
    return $Call.ByID(1168498732, options).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Search 在当前索引里查名字，按相关度排序返回
 * Search looks up names in the current index and returns them ordered by relevance
 */
export function Search(query: $models.SearchQuery): $CancellablePromise<$models.SearchResult> {
    return $Call.ByID(1519360118, query).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.IndexStats.createFrom;
const $$createType1 = $models.IndexFacets.createFrom;
const $$createType2 = $models.SearchResult.createFrom;
